language: objective-c
osx_image: xcode9
xcode_project: CIComponentKit
xcode_scheme: CIComponentKit
xcode_sdk: iphonesimulator10.3

script:
    - xcodebuild clean build -project CIComponentKit.xcodeproj -scheme CIComponentKit CODE_SIGNING_REQUIRED=NO